import evaluate
import pandas as pd

rouge = evaluate.load("rouge")
bertscore = evaluate.load("bertscore")
# predictions1 = [
#     "Pediatric anorexia nervosa (AN) is a significant public health concern in the U.S., affecting approximately 400,000 adolescents. This condition leads to severe consequences such as growth delay, bone density loss, bradycardia, and notably, it has the highest mortality rate among psychiatric conditions, with a significant proportion of deaths attributed to suicide. Despite the criticality of early intervention, current treatment approaches like Family Based Therapy (FBT), considered the gold standard, have a 50% non-response rate. A notable barrier to treatment efficacy is the role of expressed emotion (EE) in families, characterized by hostility, criticality, and emotional overinvolvement, which has been associated with poor treatment outcomes including higher dropout rates and lesser improvement in eating disorder symptoms. On the other hand, aspects like parental warmth, a component of EE, have been linked to positive outcomes in FBT. There’s also an observed gap in applying successful parenting interventions, such as emotion coaching, which have benefited other pediatric conditions, to pediatric AN cases.",
#     "The dire consequences of non-response to FBT in pediatric AN, including severe health impacts and increased mortality, underscore the necessity for improved treatment methods. This is particularly challenging as interventions like emotion coaching (EC), successful in other pediatric contexts, have not yet been explored for pediatric AN. The high EE environment in families can be a significant obstacle to effective treatment, emphasizing the need for innovative approaches to address these familial dynamics.",
#     "The dire consequences of non-response to FBT in pediatric AN, including severe health impacts and increased mortality, underscore the necessity for improved treatment methods. This is particularly challenging as interventions like emotion coaching (EC), successful in other pediatric contexts, have not yet been explored for pediatric AN. The high EE environment in families can be a significant obstacle to effective treatment, emphasizing the need for innovative approaches to address these familial dynamics.",
#     "The proposed methodology involves a two-stage approach. In the first year (Feasibility Stage), the study will test the feasibility and acceptability of the EC parent group intervention with six pediatric AN patients and their families displaying high EE. The insights gained will be used to refine the intervention content for better delivery and skill uptake. The second stage involves a randomized controlled clinical trial with 50 adolescents and their parents, comparing the outcomes of the FBT+EC group against a control group receiving FBT and standard parent support. This stage will assess the efficacy of the EC intervention in augmenting standard FBT, aiming to improve treatment outcomes for families with high EE."
# ]
# predictions2 = [
#     "Pediatric anorexia nervosa (AN), a severe psychiatric condition, is prevalent among 400,000 adolescents in the United States. It leads to serious health issues like growth delays, reduced bone density, bradycardia, and an alarmingly high mortality rate of 11.5%, with suicide accounting for half of these deaths. Timely intervention in adolescents is crucial for survival, making the treatment of pediatric AN a significant public health issue. Family-based therapy (FBT) is considered the most effective treatment for pediatric AN, yet it has a 50% non-response rate. A major hindrance to successful treatment is expressed emotion (EE) within families, characterized by hostility, critical comments, and excessive emotional involvement. Studies indicate that high EE in families negatively impacts treatment outcomes, leading to higher dropout rates, failure to regain weight, and minimal improvement in eating disorder symptoms. However, parental warmth, an aspect of EE, is linked to positive results in FBT.",
#     "The critical nature of addressing treatment non-response in medical interventions is highlighted by the severe consequences that arise from such failures. This underscores the necessity of enhancing treatments, particularly through augmentations, to effectively tackle cases of non-response. In recent developments, parenting interventions that emphasize emotion coaching (EC) have been successful when used as adjuncts to evidence-based treatments for various pediatric conditions such as PTSD and ADHD. However, these interventions have not yet been applied to pediatric Anorexia Nervosa (AN), despite their potential benefits.",
#     "The aim of the R34 pilot effectiveness trial is to carry out a two-stage study. The purpose of this study is to assess the effectiveness of a combined Family-Based Treatment (FBT) and Emotion Coaching (EC) parent group intervention within a clinical environment.",
#     "The method described involves a two-stage approach to evaluate and enhance a treatment for pediatric Anorexia Nervosa (AN). In the first year, known as the Feasibility Stage, the initial step is to test the feasibility and acceptability of an Emotion Coaching (EC) parent group intervention. This stage will involve 6 patients with pediatric AN and their families, particularly focusing on those families showing high levels of expressed emotion (EE). The data gathered from this stage will be instrumental in adjusting the content of the sessions to better deliver the treatment and facilitate the adoption of EC skills. Following the refinement and finalization of the treatment manual based on insights from the Feasibility Stage, the method progresses to Stage 2. This stage is a randomized controlled clinical trial involving 50 adolescents with AN and their parents. The trial will compare two groups: one receiving Family-Based Treatment (FBT) with the addition of the EC parent group (25 families), and the other receiving FBT with standard support (25 families). The standard support is defined as a general parent support group, which is a part of the regular offerings of the clinical Eating Disorders Program. It's important to note that the FBT provided to both groups will be identical. The only difference lies in the additional sessions – either the EC parent group sessions or the parent support group sessions – which will take place separately from the FBT sessions."
# ]
# references1 = [
#     "Pediatric anorexia nervosa (AN) affects 400,000 adolescents in the US with devastating consequences including growth delay, bone density loss, bradycardia, and the highest mortality rate of any psychiatric condition (11.5%), with half of all deaths due to suicide. Early intervention in adolescents is life-saving, making pediatric AN treatment an important public health concern. Family based therapy (FBT) is the gold standard of treatment for pediatric AN; however, 50% of patients do not respond. One barrier to treatment response in pediatric AN is expressed emotion (EE), which is defined as a family's response to an ill patient that is characterized by hostility, critical comments, and emotional overinvolvement. Several studies have highlighted that families with high EE undergoing treatment for their adolescent with AN have poorer outcomes, including higher drop-out rates, lack of weight restoration, and less improvement in eating disorder symptoms. Conversely, parental warmth, a facet of EE, is associated with good outcomes in FBT. ",
#     "The consequences of treatment non-response are dire, underscoring the importance of improving treatment via augmentations to address non-response. Recent parenting interventions focused on emotion coaching (EC) to address high EE have demonstrated success as adjuncts to evidence-based treatments in other pediatric populations (e.g., PTSD, ADHD) but have not been applied to pediatric AN.",
#     "The aim of this R34 pilot effectiveness trial is to conduct a two-stage study to evaluate the effectiveness of a FBT + EC parent group intervention within a clinical setting.",
#     "In Stage 1 (Feasibility Stage; Year 1), we will conduct preliminary feasibility and acceptability testing of an EC parent group intervention in 6 patients with pediatric AN and their families who exhibit elevated EE. The data from the Feasibility Stage will be used to modify session content to improve treatment delivery and the uptake of EC skills. Once our manual is refined and finalized, we will conduct a randomized controlled clinical trial (Stage 2) of 50 adolescents and their parents to compare FBT+EC parent group (n=25) versus FBT+support (n=25). The FBT+support condition is a general parent support group that is offered as part of standard care in our clinical Eating Disorders Program. FBT will be identical in both the treatment and control conditions, with the EC parent group sessions and parent support group sessions occurring separately from the FBT sessions."
# ]
# references2 = [
#     "Pediatric anorexia nervosa (AN) affects 400,000 adolescents in the US with devastating consequences including growth delay, bone density loss, bradycardia, and the highest mortality rate of any psychiatric condition (11.5%), with half of all deaths due to suicide. Early intervention in adolescents is life-saving, making pediatric AN treatment an important public health concern. The goal of pediatric AN treatment is to restore the adolescent back to a healthy weight and reverse the dangerous effects of malnutrition. Family based therapy (FBT) is the gold standard of treatment for pediatric AN; Several studies have highlighted that families with high EE undergoing treatment for their adolescent with AN have poorer outcomes, including higher drop-out rates, lack of weight restoration, and less improvement in eating disorder symptoms. Conversely, parental warmth, a facet of EE, is associated with good outcomes in FBT. Given the detrimental effects that high EE has on the re-feeding process and the benefits of parental warmth, emotion coaching has the potential to reduce high EE, increase parental warmth, and improve weight restoration in adolescents with AN. If the aims of the project are achieved, this study would have a large impact on pediatric AN with the potential to improve weight restoration outcomes by augmenting FBT for families high in EE.",
#     "however, 50% of patients do not respond. The consequences of treatment non-response are dire, underscoring the importance of improving treatment via augmentations to address non-response. One barrier to treatment response in pediatric AN is expressed emotion (EE), which is defined as a family's response to an ill patient that is characterized by hostility, critical comments, and emotional overinvolvement. Recent parenting interventions focused on emotion coaching (EC) to address high EE have demonstrated success as adjuncts to evidence-based treatments in other pediatric populations (e.g., PTSD, ADHD) but have not been applied to pediatric AN.",
#     "The aim of this R34 pilot effectiveness trial is to conduct a two-stage study to evaluate the effectiveness of a FBT + EC parent group intervention within a clinical setting. The data from the Feasibility Stage will be used to modify session content to improve treatment delivery and the uptake of EC skills.",
#     "Stage 1 (Feasibility Stage; Year 1), we will conduct preliminary feasibility and acceptability testing of an EC parent group intervention in 6 patients with pediatric AN and their families who exhibit elevated EE. Once our manual is refined and finalized, we will conduct a randomized controlled clinical trial (Stage 2) of 50 adolescents and their parents to compare FBT+EC parent group (n=25) versus FBT+support (n=25). The FBT+support condition is a general parent support group that is offered as part of standard care in our clinical Eating Disorders Program. FBT will be identical in both the treatment and control conditions, with the EC parent group sessions and parent support group sessions occurring separately from the FBT sessions."
# ]


def compute_bertscore(predictions, references):
    results = bertscore.compute(predictions=predictions, references=references, lang="en")
    return {
        'precision': sum(results['precision']) / len(results['precision']),
        'recall': sum(results['recall']) / len(results['recall']),
        'f1': sum(results['f1']) / len(results['f1']),
    }


predictions_cot = pd.read_csv("./data/prediction_cot.csv")
predictions_ind = pd.read_csv("./data/prediction_ind.csv")
classification = pd.read_csv("./data/classification.csv")
classification_gt = pd.read_csv("./data/classification_gt.csv")
print(rouge.compute(predictions=predictions_cot.values.flatten(), references=classification.values.flatten()))
print(compute_bertscore(predictions=predictions_cot.values.flatten(), references=classification.values.flatten()))
print(rouge.compute(predictions=predictions_cot.values.flatten(), references=classification_gt.values.flatten()))
print(compute_bertscore(predictions=predictions_cot.values.flatten(), references=classification_gt.values.flatten()))
print(rouge.compute(predictions=predictions_ind.values.flatten(), references=classification.values.flatten()))
print(compute_bertscore(predictions=predictions_ind.values.flatten(), references=classification.values.flatten()))
print(rouge.compute(predictions=predictions_ind.values.flatten(), references=classification_gt.values.flatten()))
print(compute_bertscore(predictions=predictions_ind.values.flatten(), references=classification_gt.values.flatten()))

print(rouge.compute(predictions=classification.values.flatten(), references=classification_gt.values.flatten()))
print(compute_bertscore(predictions=classification.values.flatten(), references=classification_gt.values.flatten()))

